### ISSUE TITLE
Creating a Left multi-level menu from database table

### ISSUE THREAD

**Issue by amsharma9** [mruz/base-app#32]
Hi,

Firstly, this is NOT an issue. I am trying to implement a left multi-level menu which will be generated from a database table. We should be able to close and expand it and it should be maximum 2-3 cols wide out of 12 (for whole screen). I found two references on the Internet but am not very sure how I can integrate that with base-app. If you can find time to help, that would be a big help. Here is what I found:
[Create Multi-Level menu in Phalcon] (http://stackoverflow.com/questions/27441118/create-multi-level-menu-in-phalcon) and [Buildin tree menu in Phalcon] (http://stackoverflow.com/questions/26874735/buildin-tree-menu-in-phalcon)

I got a left menu going but it is static and doesn't show up at all like what I want.

Thanks,
Amal

**Comment by amsharma9** [comment]
Mariusz,

Will it be possible for you to provide some solution. I understand you must be busy but with your expertise it shouldn't take more than half/one hour to do this. See if you can find time to provide some solution. That would be a big help.

Thanks, Amal

**Comment by mruz** [comment]
Hi Amal,

Did you see https://github.com/bendo01/Phalcon-TreeBehavior?

**Comment by mruz** [comment]
There is a few solutions based on phalconie in the network, so I close.
