### ISSUE TITLE
Using DevTools with base-app

### ISSUE THREAD

**Issue by amsharma9** [mruz/base-app#33]
Hello,

I was trying to create some models and controllers for a new project using Phalcon DevTools but it gave errors. First it gave ```Error: Adapter was not found in the config. Please specify a config variable [database][adapter]```. I created the ```adapter``` variable in ```db()``` function in *bootstrap.php*. Now it is giving me ```Error: The builder is unable to find the views directory``` when I try to run the below command:
```phalcon scaffold --table-name=ro_relorder_t  --get-set --template-engine=volt```

I think there is no variable ```modelsDir``` as given in the basic ```config.php``` file provided by Phalcon. Kindly let me know where do I specify all these directory settings.

Amal

**Comment by mruz** [comment]
I've never used Phalcon DevTools :)
Models paht is in the [Bootstrap.php#L79](https://github.com/mruz/base-app/blob/master/app/Bootstrap.php#L79)

**Comment by masterweb121** [comment]
yea, it's better directly edit base-app instead of using phalcon dev-tools.
