### ISSUE TITLE
Baseapp compatibility with Phalcon 2.x

### ISSUE THREAD

**Issue by amsharma9** [mruz/base-app#35]
Hello,

I am using Phalcon 2.0.8. If I try to use base-app with it, gives errors:
```
PHP Fatal error:  Declaration of Baseapp\Frontend\Module::registerAutoloaders() must be compatible with Phalcon\Mvc\ModuleDefinitionInterface::registerAutoloaders(Phalcon\DiInterface $dependencyInjector = NULL) in C:\Wamp\www\base-app2\app\frontend\Module.php on line 13
```
I think you need to change a few lines in Module.php and other places `registerAutoloaders() / registerServices()` are used to make it compatible to Phalcon 2.x. Saw the below solution on another post.
```
public function registerAutoloaders(\Phalcon\DiInterface $dependencyInjector = NULL) { //..... }
public function registerServices(\Phalcon\DiInterface $dependencyInjector = NULL) { //........... }
```

Amal

**Comment by mruz** [comment]
Did you try with the last commit https://github.com/mruz/base-app/commit/25c0218f657279b1639a269f37f3b4d00c196895?

**Comment by amsharma9** [comment]
Sorry for the delayed response but shouldn't the latest commit be part of app when I use "Download zip". I assumed it would be automatically included in the zip.

**Comment by mruz** [comment]
It should be. Did you download `master` branch or `2.0` tag? The latest commin in the master was on 21 Sep, maybe you had the older version? Could you try the https://github.com/mruz/base-app/archive/master.zip
