### ISSUE TITLE
Unable to change cache directory

### ISSUE THREAD

**Issue by amsharma9** [mruz/base-app#39]
Hello,

I have set cacheDir as below in config.ini but it has no effect. The cache is still created in the default directory on the local disk, i.e. ROOT_PATH"/app/common/cache/".
```
[cacheBackendFile]
adapter = "File"
options[cacheDir] = "R:/temp/"
;options[cacheDir] = ROOT_PATH"/app/common/cache/"
```
It used to work if I used the default Phalcon code and use the below line in config.php
```
'cacheDir' => 'R:/Temp/',
...
```

**Comment by mruz** [comment]
Coud you debug cache in some controller:
```php
echo (new \Phalcon\Debug\Dump([], true))->variables($this->cache); exit();
```

**Comment by amsharma9** [comment]
The debug code in IndexController gives:
```
var 0 Object Phalcon\Cache\Backend\File extends Phalcon\Cache\Backend (
  ->*_frontend (public) = Object Phalcon\Cache\Frontend\Data (
    ->*_frontendOptions (public) = Array (1) (
      [lifetime] => Numeric string (4) "3600"
    )
    Phalcon\Cache\Frontend\Data methods: (8) (
      ->__construct(); [constructor]
      ->getLifetime();
      ->isBuffering();
      ->start();
      ->getContent();
      ->stop();
      ->beforeStore();
      ->afterRetrieve();
    )
  )
  ->*_options (public) = Array (1) (
    [cacheDir] => String (8) "R:/temp/"
  )
...
```
I still don't see any files in R:\Temp and if I have some error in my php it gives error showing cache file from ROOT_PATH "/app/common/cache/".
```[25-Apr-2016 08:40:04 Asia/Calcutta] PHP Notice:  Undefined variable: show_navigation in C:\Wamp\www\base-app\app\common\cache\volt\app\frontend\views\index.phtml on line 72```

**Comment by mruz** [comment]
All is correct. I think you don't have any cache data: [Caching Output Fragments](https://docs.phalconphp.com/pl/latest/reference/cache.html#caching-output-fragments)

```php
// Get/Set the cache file to ../app/cache/my-cache.html
$content = $this->cache->start("my-cache.html");

// If $content is null then the content will be generated for the cache
if ($content === null) {

    // Print date and time
    echo date("r");

    // Generate a link to the sign-up action
    echo Tag::linkTo(
        array(
            "user/signup",
            "Sign Up",
            "class" => "signup-button"
        )
    );

    // Store the output into the cache file
    $this->cache->save();

} else {

    // Echo the cached output
    echo $content;
}
```

Maybe you thought that changing this change the volt's compiled dir, but it's specified in [Tool.php#L226](https://github.com/mruz/base-app/blob/master/app/common/library/Tool.php#L226)

**Comment by amsharma9** [comment]
I am trying to understand what you wrote. Yes, you are right I thought it was volt's compiled dir path. Is it for data? If its for data than where and how do I specify the path for volt's compiled files. Wasn't that the use for this in phalcon. This was my config.php in phalcon which used to change the compiled path:
```
return new \Phalcon\Config(array(
    'database' => array(
        'adapter' => 'Mysql',
        'host' => 'localhost',
        'username' => 'xxx',
        'password' => 'yyy',
        'dbname' => 'testdb'
    ),
    'application' => array(
        'controllersDir' => APP_DIR . '/controllers/',
        'modelsDir' => APP_DIR . '/models/',
        'formsDir' => APP_DIR . '/forms/',
        'viewsDir' => APP_DIR . '/views/',
        'libraryDir' => APP_DIR . '/library/',
        'pluginsDir' => APP_DIR . '/plugins/',
        'cacheDir' => 'R:/Temp/',
        'baseUri' => '/res/',
```

**Comment by amsharma9** [comment]
How and where do I change the "compiledPath" in baseapp using config.ini.

**Comment by mruz** [comment]
Now you can change `compiledPath` in `config.ini`:
``ini
[view]
compiledPath = "R:/Temp/"
compiledExtension = ".phtml"
```

**Comment by amsharma9** [comment]
There is an error:
```[26-Apr-2016 14:20:21 Asia/Calcutta] PHP Fatal error:  Using $this when not in object context in C:\Wamp\www\baseapp\app\common\library\Tool.php on line 221```

**Comment by mruz** [comment]
Now it should work.
